//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.17929
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourcesLibrary {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayLabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayLabels() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourcesLibrary.DisplayLabels", typeof(DisplayLabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Additional fields.
        /// </summary>
        public static string AdditionalFieldsGroupBox {
            get {
                return ResourceManager.GetString("AdditionalFieldsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AssignDataWindow.
        /// </summary>
        public static string AssignDataWindowTitle {
            get {
                return ResourceManager.GetString("AssignDataWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на AssignWindow.
        /// </summary>
        public static string AssignWindowTitle {
            get {
                return ResourceManager.GetString("AssignWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Authentication.
        /// </summary>
        public static string AuthenticationGroupBox {
            get {
                return ResourceManager.GetString("AuthenticationGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CanceledMark.
        /// </summary>
        public static string CanceledMarkCheckBox {
            get {
                return ResourceManager.GetString("CanceledMarkCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel test.
        /// </summary>
        public static string CancelTest {
            get {
                return ResourceManager.GetString("CancelTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correct .
        /// </summary>
        public static string CorrectAnswerButton {
            get {
                return ResourceManager.GetString("CorrectAnswerButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Correct answers:.
        /// </summary>
        public static string CorrectAnswersLabel {
            get {
                return ResourceManager.GetString("CorrectAnswersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на created by.
        /// </summary>
        public static string CreatedByLabel {
            get {
                return ResourceManager.GetString("CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Date.
        /// </summary>
        public static string DateDataGrid {
            get {
                return ResourceManager.GetString("DateDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на DeGrouping.
        /// </summary>
        public static string DeGroupingButton {
            get {
                return ResourceManager.GetString("DeGroupingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detail....
        /// </summary>
        public static string DetailButton {
            get {
                return ResourceManager.GetString("DetailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Details.
        /// </summary>
        public static string DetailsDataGrid {
            get {
                return ResourceManager.GetString("DetailsDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Detail....
        /// </summary>
        public static string DetailStatisticButton {
            get {
                return ResourceManager.GetString("DetailStatisticButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Down.
        /// </summary>
        public static string DownButton {
            get {
                return ResourceManager.GetString("DownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email:.
        /// </summary>
        public static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Finish test.
        /// </summary>
        public static string FinishTest {
            get {
                return ResourceManager.GetString("FinishTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Forgot password.
        /// </summary>
        public static string ForgotPasswordButton {
            get {
                return ResourceManager.GetString("ForgotPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Grouping.
        /// </summary>
        public static string GroupingButton {
            get {
                return ResourceManager.GetString("GroupingButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group:.
        /// </summary>
        public static string GroupLabel {
            get {
                return ResourceManager.GetString("GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Group Name.
        /// </summary>
        public static string GroupNameDataGrid {
            get {
                return ResourceManager.GetString("GroupNameDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter Code:.
        /// </summary>
        public static string InputCodeLabel {
            get {
                return ResourceManager.GetString("InputCodeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter New Password:.
        /// </summary>
        public static string InputNewPasswordLabel {
            get {
                return ResourceManager.GetString("InputNewPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter You Username:.
        /// </summary>
        public static string InputUsernameLabel {
            get {
                return ResourceManager.GetString("InputUsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на IsCorrect.
        /// </summary>
        public static string IsCorrectDataGrid {
            get {
                return ResourceManager.GetString("IsCorrectDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result: .
        /// </summary>
        public static string IsPassedLabel {
            get {
                return ResourceManager.GetString("IsPassedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на LearningMode.
        /// </summary>
        public static string LearningModeRadioButton {
            get {
                return ResourceManager.GetString("LearningModeRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle Name:.
        /// </summary>
        public static string MiddleNameLabel {
            get {
                return ResourceManager.GetString("MiddleNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ModulActionWindow.
        /// </summary>
        public static string ModulActionWindowTitle {
            get {
                return ResourceManager.GetString("ModulActionWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moduls.
        /// </summary>
        public static string ModulsButton {
            get {
                return ResourceManager.GetString("ModulsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Moduls Window.
        /// </summary>
        public static string ModulsWindowTitle {
            get {
                return ResourceManager.GetString("ModulsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name:.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Navigtion.
        /// </summary>
        public static string NavigtionMenuItem {
            get {
                return ResourceManager.GetString("NavigtionMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next.
        /// </summary>
        public static string NextButton {
            get {
                return ResourceManager.GetString("NextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Next Step.
        /// </summary>
        public static string NextStepButton {
            get {
                return ResourceManager.GetString("NextStepButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OKButton {
            get {
                return ResourceManager.GetString("OKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OrdinalNumber.
        /// </summary>
        public static string OrdinalNumberDataGrid {
            get {
                return ResourceManager.GetString("OrdinalNumberDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password:.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Prev.
        /// </summary>
        public static string PrevButton {
            get {
                return ResourceManager.GetString("PrevButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Profile.
        /// </summary>
        public static string ProfileButton {
            get {
                return ResourceManager.GetString("ProfileButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfileDataWindow.
        /// </summary>
        public static string ProfileDataWindowTitle {
            get {
                return ResourceManager.GetString("ProfileDataWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ProfilesWindow.
        /// </summary>
        public static string ProfilesWindowTitle {
            get {
                return ResourceManager.GetString("ProfilesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string QuestionPassedNo {
            get {
                return ResourceManager.GetString("QuestionPassedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string QuestionPassedYes {
            get {
                return ResourceManager.GetString("QuestionPassedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Questions.
        /// </summary>
        public static string QuestionsGroupBox {
            get {
                return ResourceManager.GetString("QuestionsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RatingScaleDataWindow.
        /// </summary>
        public static string RatingScaleDataWindowTitle {
            get {
                return ResourceManager.GetString("RatingScaleDataWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RatingScalesWindow.
        /// </summary>
        public static string RatingScalesWindowTitle {
            get {
                return ResourceManager.GetString("RatingScalesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register New Account.
        /// </summary>
        public static string RegisterNewAccountButton {
            get {
                return ResourceManager.GetString("RegisterNewAccountButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register New User.
        /// </summary>
        public static string RegisterNewUserTitle {
            get {
                return ResourceManager.GetString("RegisterNewUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Required fields.
        /// </summary>
        public static string RequiredFieldsGroupBox {
            get {
                return ResourceManager.GetString("RequiredFieldsGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Reset User Password.
        /// </summary>
        public static string ResetUserPasswordTitle {
            get {
                return ResourceManager.GetString("ResetUserPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Result.
        /// </summary>
        public static string ResultDataGrid {
            get {
                return ResourceManager.GetString("ResultDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save New Password.
        /// </summary>
        public static string SaveNewPasswordButton {
            get {
                return ResourceManager.GetString("SaveNewPasswordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Scientia Potentia Est.
        /// </summary>
        public static string ScientiaPotentiaEstTitle {
            get {
                return ResourceManager.GetString("ScientiaPotentiaEstTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set mode.
        /// </summary>
        public static string SetMode {
            get {
                return ResourceManager.GetString("SetMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set Mode Window.
        /// </summary>
        public static string SetModeWindowTitle {
            get {
                return ResourceManager.GetString("SetModeWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set subject.
        /// </summary>
        public static string SetSubject {
            get {
                return ResourceManager.GetString("SetSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to set the subject.
        /// </summary>
        public static string SetSubjectGroupBox {
            get {
                return ResourceManager.GetString("SetSubjectGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SetSubjectWindow.
        /// </summary>
        public static string SetSubjectWindowTitle {
            get {
                return ResourceManager.GetString("SetSubjectWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have to set the test mode.
        /// </summary>
        public static string SetTestModeGroupBox {
            get {
                return ResourceManager.GetString("SetTestModeGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Setting.
        /// </summary>
        public static string SettingMenuItem {
            get {
                return ResourceManager.GetString("SettingMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show RatingScales.
        /// </summary>
        public static string ShowRatingScalesButton {
            get {
                return ResourceManager.GetString("ShowRatingScalesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign in.
        /// </summary>
        public static string SignInButton {
            get {
                return ResourceManager.GetString("SignInButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign Out.
        /// </summary>
        public static string SignOutButton {
            get {
                return ResourceManager.GetString("SignOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start test.
        /// </summary>
        public static string StartTest {
            get {
                return ResourceManager.GetString("StartTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistic.
        /// </summary>
        public static string StatisticButton {
            get {
                return ResourceManager.GetString("StatisticButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistics.
        /// </summary>
        public static string StatisticsTest {
            get {
                return ResourceManager.GetString("StatisticsTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на StatisticStudentWindow.
        /// </summary>
        public static string StatisticStudentWindowTitle {
            get {
                return ResourceManager.GetString("StatisticStudentWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Statistic Test Window.
        /// </summary>
        public static string StatisticTestWindowTitle {
            get {
                return ResourceManager.GetString("StatisticTestWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step 1.
        /// </summary>
        public static string StepOneGroupBox {
            get {
                return ResourceManager.GetString("StepOneGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Step 2.
        /// </summary>
        public static string StepTwoGroupBox {
            get {
                return ResourceManager.GetString("StepTwoGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Student Name.
        /// </summary>
        public static string StudentNameDataGrid {
            get {
                return ResourceManager.GetString("StudentNameDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SubjectActionWindow.
        /// </summary>
        public static string SubjectActionWindoTitle {
            get {
                return ResourceManager.GetString("SubjectActionWindoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Subject.
        /// </summary>
        public static string SubjectLabel {
            get {
                return ResourceManager.GetString("SubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SubjectsWindow.
        /// </summary>
        public static string SubjectsWindowTitle {
            get {
                return ResourceManager.GetString("SubjectsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Surname:.
        /// </summary>
        public static string SurnameLabel {
            get {
                return ResourceManager.GetString("SurnameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на I am a teacher.
        /// </summary>
        public static string TeacherCheckBox {
            get {
                return ResourceManager.GetString("TeacherCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Teacher Name.
        /// </summary>
        public static string TeacherNameDataGrid {
            get {
                return ResourceManager.GetString("TeacherNameDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TeacherWindow.
        /// </summary>
        public static string TeacherWindowTitle {
            get {
                return ResourceManager.GetString("TeacherWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Test for.
        /// </summary>
        public static string TestForLabel {
            get {
                return ResourceManager.GetString("TestForLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TESTING.
        /// </summary>
        public static string TESTINGButton {
            get {
                return ResourceManager.GetString("TESTINGButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TestingMode.
        /// </summary>
        public static string TestingModeRadioButton {
            get {
                return ResourceManager.GetString("TestingModeRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TestingWindow.
        /// </summary>
        public static string TestingWindowTitle {
            get {
                return ResourceManager.GetString("TestingWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на _Test.
        /// </summary>
        public static string TestMenuItem {
            get {
                return ResourceManager.GetString("TestMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed.
        /// </summary>
        public static string TestPassedNo {
            get {
                return ResourceManager.GetString("TestPassedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passed.
        /// </summary>
        public static string TestPassedYes {
            get {
                return ResourceManager.GetString("TestPassedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Title.
        /// </summary>
        public static string TitleDataGrid {
            get {
                return ResourceManager.GetString("TitleDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Up.
        /// </summary>
        public static string UpButton {
            get {
                return ResourceManager.GetString("UpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User info.
        /// </summary>
        public static string UserInfoGroupBox {
            get {
                return ResourceManager.GetString("UserInfoGroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User:.
        /// </summary>
        public static string UserLabel {
            get {
                return ResourceManager.GetString("UserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User:.
        /// </summary>
        public static string UsernameLabel {
            get {
                return ResourceManager.GetString("UsernameLabel", resourceCulture);
            }
        }
    }
}
